/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbtpos;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Arrays;
import java.nio.file.*;

/**
 *
 * @author theri
 */
public class MainWindow extends javax.swing.JFrame {
    
    @SuppressWarnings("FieldMayBeFinal")
    private OrderItem[] currentOrder;
    private int numItems;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        btnO.setActionCommand(btnO.getText());
        btnP.setActionCommand(btnP.getText());
        btnS.setActionCommand(btnS.getText());
        btnT.setActionCommand(btnT.getText());
        btnL.setActionCommand(btnL.getText());
        btnN.setActionCommand(btnN.getText());
        btnB.setActionCommand(btnB.getText());
        btn2T.setActionCommand(btn2T.getText());
        btn2L.setActionCommand(btn2L.getText());
        currentOrder = new OrderItem[5];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmDialog = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        btnOrderConf = new javax.swing.JButton();
        btnOrderCan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tenderDisp = new javax.swing.JTextField();
        changeDisp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        menuSelect = new javax.swing.ButtonGroup();
        toppingSelect = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        payDisp = new javax.swing.JTextField();
        orderDisp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnD0 = new javax.swing.JButton();
        btnO = new javax.swing.JToggleButton();
        btnP = new javax.swing.JToggleButton();
        btnT = new javax.swing.JToggleButton();
        btnL = new javax.swing.JToggleButton();
        btnN = new javax.swing.JToggleButton();
        btnB = new javax.swing.JToggleButton();
        btn2T = new javax.swing.JToggleButton();
        btn2L = new javax.swing.JToggleButton();
        btnAdd = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnS = new javax.swing.JToggleButton();

        confirmDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        confirmDialog.setAlwaysOnTop(true);
        confirmDialog.setMinimumSize(new java.awt.Dimension(420, 473));
        confirmDialog.setResizable(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm Order");

        btnOrderConf.setBackground(new java.awt.Color(80, 163, 11));
        btnOrderConf.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnOrderConf.setText("✓");
        btnOrderConf.setPreferredSize(new java.awt.Dimension(125, 80));
        btnOrderConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderConfActionPerformed(evt);
            }
        });

        btnOrderCan.setBackground(new java.awt.Color(243, 43, 31));
        btnOrderCan.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnOrderCan.setText("X");
        btnOrderCan.setPreferredSize(new java.awt.Dimension(125, 80));
        btnOrderCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderCanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Payment");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("No refunds/changes after confirmation.");
        jLabel7.setToolTipText("");

        tenderDisp.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        tenderDisp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tenderDisp.setText("$0.00");
        tenderDisp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tenderDisp.setEnabled(false);

        changeDisp.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        changeDisp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        changeDisp.setText("$0.00");
        changeDisp.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        changeDisp.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tender");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Change");

        javax.swing.GroupLayout confirmDialogLayout = new javax.swing.GroupLayout(confirmDialog.getContentPane());
        confirmDialog.getContentPane().setLayout(confirmDialogLayout);
        confirmDialogLayout.setHorizontalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnOrderCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmDialogLayout.createSequentialGroup()
                        .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(confirmDialogLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tenderDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(confirmDialogLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        confirmDialogLayout.setVerticalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tenderDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)))
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrderCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Toppings");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bubble Tea POS");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Bubble Tea POS");

        btn1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(80, 80));
        btn1.setMinimumSize(new java.awt.Dimension(80, 80));
        btn1.setPreferredSize(new java.awt.Dimension(80, 80));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn2.setLabel("2");
        btn2.setMaximumSize(new java.awt.Dimension(80, 80));
        btn2.setMinimumSize(new java.awt.Dimension(80, 80));
        btn2.setPreferredSize(new java.awt.Dimension(80, 80));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn3.setLabel("3");
        btn3.setMaximumSize(new java.awt.Dimension(80, 80));
        btn3.setMinimumSize(new java.awt.Dimension(80, 80));
        btn3.setPreferredSize(new java.awt.Dimension(80, 80));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn4.setLabel("4");
        btn4.setMaximumSize(new java.awt.Dimension(80, 80));
        btn4.setMinimumSize(new java.awt.Dimension(80, 80));
        btn4.setPreferredSize(new java.awt.Dimension(80, 80));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn5.setLabel("5");
        btn5.setMaximumSize(new java.awt.Dimension(80, 80));
        btn5.setMinimumSize(new java.awt.Dimension(80, 80));
        btn5.setPreferredSize(new java.awt.Dimension(80, 80));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn7.setLabel("7");
        btn7.setMaximumSize(new java.awt.Dimension(80, 80));
        btn7.setMinimumSize(new java.awt.Dimension(80, 80));
        btn7.setPreferredSize(new java.awt.Dimension(80, 80));
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn6.setLabel("6");
        btn6.setMaximumSize(new java.awt.Dimension(80, 80));
        btn6.setMinimumSize(new java.awt.Dimension(80, 80));
        btn6.setPreferredSize(new java.awt.Dimension(80, 80));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn8.setLabel("8");
        btn8.setMaximumSize(new java.awt.Dimension(80, 80));
        btn8.setMinimumSize(new java.awt.Dimension(80, 80));
        btn8.setPreferredSize(new java.awt.Dimension(80, 80));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn9.setLabel("9");
        btn9.setMaximumSize(new java.awt.Dimension(80, 80));
        btn9.setMinimumSize(new java.awt.Dimension(80, 80));
        btn9.setPreferredSize(new java.awt.Dimension(80, 80));
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn0.setLabel("0");
        btn0.setMaximumSize(new java.awt.Dimension(80, 80));
        btn0.setMinimumSize(new java.awt.Dimension(80, 80));
        btn0.setPreferredSize(new java.awt.Dimension(80, 80));
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnG.setBackground(new java.awt.Color(80, 163, 11));
        btnG.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnG.setLabel("✓");
        btnG.setMaximumSize(new java.awt.Dimension(80, 80));
        btnG.setMinimumSize(new java.awt.Dimension(80, 80));
        btnG.setPreferredSize(new java.awt.Dimension(80, 80));
        btnG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGMouseClicked(evt);
            }
        });
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(243, 43, 31));
        btnC.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnC.setLabel("C");
        btnC.setMaximumSize(new java.awt.Dimension(80, 80));
        btnC.setMinimumSize(new java.awt.Dimension(80, 80));
        btnC.setPreferredSize(new java.awt.Dimension(80, 80));
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCMouseClicked(evt);
            }
        });
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(36, 133, 169));
        btnE.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnE.setText("E");
        btnE.setMaximumSize(new java.awt.Dimension(252, 80));
        btnE.setMinimumSize(new java.awt.Dimension(80, 80));
        btnE.setPreferredSize(new java.awt.Dimension(80, 80));
        btnE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEMouseClicked(evt);
            }
        });
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        payDisp.setColumns(6);
        payDisp.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        payDisp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payDisp.setText("$0.00");
        payDisp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        payDisp.setEnabled(false);

        orderDisp.setColumns(6);
        orderDisp.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        orderDisp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderDisp.setText("$0.00");
        orderDisp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        orderDisp.setEnabled(false);
        orderDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDispActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Payment");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add to Order");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnD0.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnD0.setText(".00");
        btnD0.setMaximumSize(new java.awt.Dimension(80, 80));
        btnD0.setMinimumSize(new java.awt.Dimension(80, 80));
        btnD0.setPreferredSize(new java.awt.Dimension(80, 80));
        btnD0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnD0MouseClicked(evt);
            }
        });
        btnD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD0ActionPerformed(evt);
            }
        });

        menuSelect.add(btnO);
        btnO.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnO.setText("Original");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });

        menuSelect.add(btnP);
        btnP.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnP.setText("PF");
        btnP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPMouseClicked(evt);
            }
        });
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        toppingSelect.add(btnT);
        btnT.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnT.setText("T");
        btnT.setPreferredSize(new java.awt.Dimension(122, 63));
        btnT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTMouseClicked(evt);
            }
        });
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        toppingSelect.add(btnL);
        btnL.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnL.setText("L");
        btnL.setPreferredSize(new java.awt.Dimension(122, 63));
        btnL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLMouseClicked(evt);
            }
        });
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        toppingSelect.add(btnN);
        btnN.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnN.setText("0");
        btnN.setPreferredSize(new java.awt.Dimension(122, 63));
        btnN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNMouseClicked(evt);
            }
        });
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });

        toppingSelect.add(btnB);
        btnB.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnB.setText("T+L");
        btnB.setPreferredSize(new java.awt.Dimension(122, 63));
        btnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBMouseClicked(evt);
            }
        });
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        toppingSelect.add(btn2T);
        btn2T.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn2T.setText("2T");
        btn2T.setPreferredSize(new java.awt.Dimension(122, 63));
        btn2T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2TMouseClicked(evt);
            }
        });
        btn2T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2TActionPerformed(evt);
            }
        });

        toppingSelect.add(btn2L);
        btn2L.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btn2L.setText("2L");
        btn2L.setPreferredSize(new java.awt.Dimension(122, 63));
        btn2L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2LMouseClicked(evt);
            }
        });
        btn2L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2LActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(80, 163, 11));
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAdd.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Summary");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        orderTable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "D", "T", "P"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setRowHeight(55);
        orderTable.getTableHeader().setResizingAllowed(false);
        orderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(orderTable);

        btnRemove.setBackground(new java.awt.Color(243, 43, 31));
        btnRemove.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setMaximumSize(new java.awt.Dimension(80, 80));
        btnRemove.setMinimumSize(new java.awt.Dimension(80, 80));
        btnRemove.setPreferredSize(new java.awt.Dimension(80, 80));
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        menuSelect.add(btnS);
        btnS.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnS.setText("Slush");
        btnS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSMouseClicked(evt);
            }
        });
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn2T, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn2L, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(orderDisp)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnD0, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(payDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnD0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn2T, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2L, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn2MouseClicked

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        addDigit(2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn3MouseClicked

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        addDigit(3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn4MouseClicked

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        addDigit(4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn5MouseClicked

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        addDigit(5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn7MouseClicked

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        addDigit(7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn6MouseClicked

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        addDigit(6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn8MouseClicked

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        addDigit(8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn9MouseClicked

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        addDigit(9);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn0MouseClicked

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        addDigit(0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGMouseClicked

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        processOrder();
    }//GEN-LAST:event_btnGActionPerformed

    private void btnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCMouseClicked

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        payDisp.setText("$0.00");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEMouseClicked

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        payDisp.setText(orderDisp.getText());
    }//GEN-LAST:event_btnEActionPerformed

    private void btnD0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnD0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD0MouseClicked

    private void btnD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD0ActionPerformed
        // TODO add your handling code here:
        addDigit(0.1);
    }//GEN-LAST:event_btnD0ActionPerformed

    private void orderDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderDispActionPerformed

    private void btnPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPMouseClicked

    private void btnTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTMouseClicked

    private void btnLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLMouseClicked

    private void btnNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNMouseClicked

    private void btnBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBMouseClicked

    private void btn2TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2TMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2TMouseClicked

    private void btn2LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2LMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2LMouseClicked

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBActionPerformed

    private void btn2TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2TActionPerformed

    private void btn2LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2LActionPerformed

    }//GEN-LAST:event_btn2LActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        addDigit(1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToOrder();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked

    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeFromOrder();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOrderConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderConfActionPerformed
        outputToCSV();
        clearDisp();
        confirmDialog.setVisible(false);
    }//GEN-LAST:event_btnOrderConfActionPerformed

    private void btnOrderCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderCanActionPerformed
        confirmDialog.setVisible(false);
    }//GEN-LAST:event_btnOrderCanActionPerformed

    private void btnSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSMouseClicked

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // Methods
    private void clearDisp() {
        payDisp.setText("$0.00");
        orderDisp.setText("$0.00");
        menuSelect.clearSelection();
        toppingSelect.clearSelection();
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        orderTable.setModel(model);
        btnAdd.setEnabled(true);
        for (int i = 0; i < 5; i++) {
            currentOrder[i] = null;
        }
        numItems = 0;
    }
    
    private void addDigit(double digit) {
        double currentVal = Double.parseDouble((payDisp.getText()).replaceAll("[^\\d.]", ""));
        double tempVal = currentVal;
        if (digit == 0.1) {
            // 0.1 is a 'key value' so that I don't have to pass an extra
            // parameter for this operation - it's normally not possible
            // for the digit to be a non-integer.
            currentVal *= 100;
        }
        else {
            if (digit != 0) {
                digit /= 100;
            }
            currentVal += (currentVal * 10);
            currentVal -= tempVal;
            currentVal += digit;
        }
        
        String output = "$" + String.format("%.2f", currentVal);
        payDisp.setText(output);
    }
    
    private void addToOrder() {
        String menuItem;
        String toppingItem;
        double menuPrice;
        double toppingPrice;
        double itemPrice;
        
        try {
            menuItem = menuSelect.getSelection().getActionCommand();
        }
        catch (NullPointerException e) {
            return;
        }
        try {
            toppingItem = toppingSelect.getSelection().getActionCommand();
        } catch (NullPointerException e) {
            return;
        }
        
        switch (menuItem) {
            case "Original":
                menuPrice = 3;
                menuItem = "O";
                break;
            case "PF":
                menuPrice = 3;
                menuItem = "P";
                break;
            case "Slush":
                menuPrice = 4;
                menuItem = "S";
                break;
            default:
                menuPrice = 0;
                break;
        }
        
        switch (toppingItem) {
            case "T": case "L":
                toppingPrice = 0.5;
                break;
            case "T+L": case "2T": case "2L":
                toppingPrice = 1;
                break;
            default:
                toppingPrice = 0;
                break;
        }
        itemPrice = menuPrice + toppingPrice;
        if (numItems == 4) {
            btnAdd.setEnabled(false);
        }
        currentOrder[numItems] = new OrderItem((numItems + 1), menuItem, toppingItem, itemPrice);
        numItems += 1;
        
        setOrderDisp(itemPrice);
        updateTable();
        menuSelect.clearSelection();
        toppingSelect.clearSelection();
    }
    
    private void removeFromOrder() {
        int rowToRemove = orderTable.getSelectedRow();
        double removePrice = currentOrder[rowToRemove].getPrice() * -1;
        try {
                for (int i = rowToRemove; i <= 4; i++) {
                    if (rowToRemove == 4 || currentOrder[i + 1] == null) {
                        currentOrder[i] = null;
                        break;
                    }
                    else {
                        currentOrder[i] = currentOrder[i + 1];
                        currentOrder[i + 1] = null;
                        currentOrder[i].decPos();
                    }
                   }  
            setOrderDisp(removePrice);
            numItems -= 1;
            if (numItems < 4) {
                btnAdd.setEnabled(true);
            }
            updateTable();
        }
        catch (ArrayIndexOutOfBoundsException e) {
            setOrderDisp(removePrice);
            numItems -= 1;
            if (numItems < 4) {
                btnAdd.setEnabled(true);
            }
            updateTable();}
    }
    
    private void setOrderDisp(double aToAdd) {
        double totalPrice;
        double orderAmt = Double.parseDouble((orderDisp.getText()).replaceAll("[^\\d.]", ""));
        totalPrice = orderAmt + aToAdd;
        String output = "$" + String.format("%.2f", totalPrice);
        orderDisp.setText(output);
    }
    
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < 5; i++) {
            try {
                model.addRow(currentOrder[i].outputItem());
            }
            catch (NullPointerException e) {}
        }
        orderTable.setModel(model);
    }
    
    private void processOrder() {
        double orderAmt = Double.parseDouble((orderDisp.getText()).replaceAll("[^\\d.]", ""));
        double payAmt = Double.parseDouble((payDisp.getText()).replaceAll("[^\\d.]", ""));
        
        if (orderAmt <= 1) {
            System.out.println("invalid order");
        }
        
        else if (payAmt >= orderAmt) {
            // Confirm dialog
            confirmDialog.setLocationRelativeTo(null);
            confirmDialog.setVisible(true);
            tenderDisp.setText(payDisp.getText());
            double change = payAmt - orderAmt;
            String changeOut = "$" + String.format("%.2f", change);
            changeDisp.setText(changeOut);
        }
        else {
            // Error dialog
            // return;
            System.out.println("Too little");
        }
    }
    
    private void outputToCSV() {
        String currentDateTime = new SimpleDateFormat("yyyy-MM-dd HH").format(new Date());
        String currentTime = new SimpleDateFormat("HH:mm:ss").format(new Date());
        String filename = "Order Logs/" + currentDateTime + ".csv";
        String orderString = currentTime;
        try {
            for (int i = 0; i < 5; i++) {
                orderString = orderString + "\n," + orderTable.getValueAt(i, 1).toString() + "," + orderTable.getValueAt(i, 2).toString() + "," + orderTable.getValueAt(i, 3);
            }
        } catch (ArrayIndexOutOfBoundsException e) {}
        orderString = orderString + "," + orderDisp.getText() + "," + tenderDisp.getText() + "," + changeDisp.getText();
        try {
            final Path path = Paths.get(filename);
            Files.write(path, Arrays.asList(orderString), StandardCharsets.UTF_8, Files.exists(path) ? StandardOpenOption.APPEND : StandardOpenOption.CREATE);
        } catch (IOException ioe) {System.out.println("IOEXCEPTION - REPEAT THE ORDER. You didn't forget to close the csv file, did you?");}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JToggleButton btn2L;
    private javax.swing.JToggleButton btn2T;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JToggleButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD0;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnG;
    private javax.swing.JToggleButton btnL;
    private javax.swing.JToggleButton btnN;
    private javax.swing.JToggleButton btnO;
    private javax.swing.JButton btnOrderCan;
    private javax.swing.JButton btnOrderConf;
    private javax.swing.JToggleButton btnP;
    private javax.swing.JButton btnRemove;
    private javax.swing.JToggleButton btnS;
    private javax.swing.JToggleButton btnT;
    private javax.swing.JTextField changeDisp;
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.ButtonGroup menuSelect;
    private javax.swing.JTextField orderDisp;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField payDisp;
    private javax.swing.JTextField tenderDisp;
    private javax.swing.ButtonGroup toppingSelect;
    // End of variables declaration//GEN-END:variables
}
